
version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3003:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_PATH=/app/data/db.sqlite
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/callback
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_REDIRECT_URL=${MICROSOFT_REDIRECT_URL}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
    volumes:
      - ./data:/app/data
    depends_on:
      - redis

  processor-service:
    build:
      context: ./processor-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_SERVICE_URL=http://api-service:3000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
    depends_on:
      - redis
      - api-service
